large:
  results_dir: /content/VAE/drive/MyDrive/ECE695/project/results/large
  dataset_name: mc_maze_large
  data_dir: /content/VAE/drive/MyDrive/ECE695/project/mc_maze_data/000138/sub-Jenkins/ 
  in_units: 122     
  out_units: 162
  t_out: 180
  latent_dim: 100
  drop: 0.2    
medium:
  results_dir: /content/VAE/drive/MyDrive/ECE695/project/results/medium
  dataset_name: mc_maze_medium
  data_dir: /content/VAE/drive/MyDrive/ECE695/project/mc_maze_data/000139/sub-Jenkins/ 
  in_units: 114     
  out_units: 152
  t_out: 180
  latent_dim: 100
  drop: 0.2 
small:
  results_dir: /content/VAE/drive/MyDrive/ECE695/project/results/small
  dataset_name: mc_maze_small
  data_dir: /content/VAE/drive/MyDrive/ECE695/project/mc_maze_data/000140/sub-Jenkins/ 
  in_units: 104     
  out_units: 142
  t_out: 180
  latent_dim: 100
  drop: 0.2   


hyper_param:
  epochs: 1000
  batch_size: 32
  lr: 1.0e-4
  wd: 0
  load_weights: False
