large:
  results_dir: ./results/large
  dataset_name: mc_maze_large
  data_dir: ./data/000138/sub-Jenkins/ 
  in_units: 122     
  out_units: 162
  t_out: 180
  latent_dim: 100
  drop: 0.2    
medium:
  results_dir: ./results/medium
  dataset_name: mc_maze_medium
  data_dir: /data/000139/sub-Jenkins/ 
  in_units: 114     
  out_units: 152
  t_out: 180
  latent_dim: 100
  drop: 0.2 
small:
  results_dir: ./results/small
  dataset_name: mc_maze_small
  data_dir: /data/000140/sub-Jenkins/ 
  in_units: 104     
  out_units: 142
  t_out: 180
  latent_dim: 100
  drop: 0.2   


hyper_param:
  epochs: 1000
  batch_size: 32
  lr: 0.0005
  wd: 5.0e-8
  cd_ratio: 0.27
  hidden_dim: 32
  drop: 0.4
  load_weights: False
